# Generated by Django 4.0.5 on 2022-08-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
